### PR TITLE
Update TJ-bot image

### LINKED ISSUE #13: Update Bot details on website
[The website](https://togetherjava.org/) still shows that TJ-Bot uses java 18 while we recently upgraded to Java 20. We should update this.

### PR DESCRIPTION
**Pull request by java-coding-prodigy**
Fixes #13

### CODE REVIEW

**Review by Zabuzard — CHANGES_REQUESTED** [review]
This changes the sizes and resolution dramatically. please scale it down

**Comment by java-coding-prodigy** [comment]
Should both the width and height be same or only the width? 
Maybe I could also change the css files a bit to accommodate the image?

**Comment by Zabuzard** [comment]
1. if the file is large, the site takes longer to load, google doesnt like that, we get indexed lower
2. whatever u do, make sure it still looks the same way in the actual website on all resolutions. i could imagine that the website code either doesnt take care of resizing right now, or that it forces a hard resolution anyways

**Comment by java-coding-prodigy** [comment]
I will need to know what device the original image was taken to have the same text wrapping which is needed if the dimensions need to be the same.
It looks like it was taken on a cell phone.

**Comment by java-coding-prodigy** [comment]
I have shrunk the image. The dimensions are nearly the same and the size has been reduced.
However the quality is not as good

**Comment by Zabuzard** [comment]
can u share how it looks on the website? full hd and also on a mobile view please

**Comment by java-coding-prodigy** [comment]
> can u share how it looks on the website? full hd and also on a mobile view please

How would I host the website tho?

**Review by Zabuzard — APPROVED** [review]

**Pull request merged**
